### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by CarlosIgreda** [federicaulzurrun/AwesomeBooks#4]
Hi @federicaulzurrun  ,

Good job so far! 🚀 
There are some issues that you still need to work on to improve your code, but you are almost there! 👌 

![tufoin](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights
✅  No linter errors 
✅  Your page is working as expected
✅  Commits are descriptive
✅  Correct GitHub Flow

## Required Changes ♻️
Kindly consider using the `<br>` instead of the `<span>` (Lines 20 and 22), because the element `<span>` is not allowed as a child of element `<ul>` in this context. (Suppressing further errors from this subtree).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this issue. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in this issue thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by federicaulzurrun** [comment]
thanks for your suggestions!!
